"""Initial schema: contacts, conversations, messages, templates, cooldowns, agent_registrations

Revision ID: f7cf8e463916
Revises: 
Create Date: 2026-04-02 21:17:55.691048
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f7cf8e463916'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Agent name (e.g., helmtech-outreach, apex-outreach)'),
    sa.Column('callback_url', sa.String(length=500), nullable=False, comment='URL to POST inbound messages to (e.g., http://localhost:8003/webhooks/whatsapp)'),
    sa.Column('api_key', sa.String(length=200), nullable=False, comment='Key the agent uses to authenticate with the gateway'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1-10, higher = gets first pick when routing ambiguous messages'),
    sa.Column('claim_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rules for claiming unassigned contacts: {phone_prefixes: [], keywords: []}'),
    sa.Column('daily_limit', sa.Integer(), nullable=False, comment='Max outbound messages this agent can send per day'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_registrations_name'), 'agent_registrations', ['name'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='E.164 format (e.g., +919876543210)'),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True, comment='ISO country code (e.g., IN, US)'),
    sa.Column('source_agent', sa.String(length=100), nullable=False, comment='Agent that created this contact first'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False, comment='e.g., en, hi, en_US'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='marketing, utility, authentication'),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Template components as returned by Meta API'),
    sa.Column('meta_status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='templatestatus'), nullable=False),
    sa.Column('agent_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Which agents can use this template (empty = all)'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('owning_agent', sa.String(length=100), nullable=True, comment='Agent that owns this conversation (handles replies). Null = unassigned.'),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'CLOSED', name='conversationstatus'), nullable=False),
    sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the 24hr session window expires. Set on every inbound message.'),
    sa.Column('last_customer_message_at', sa.DateTime(timezone=True), nullable=True, comment='When the customer last sent a message.'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='When any message (in or out) was last exchanged.'),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_contact_id'), 'conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversations_owning_agent'), 'conversations', ['owning_agent'], unique=False)
    op.create_table('cooldowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'agent_name', name='uq_cooldown_contact_agent')
    )
    op.create_index(op.f('ix_cooldowns_agent_name'), 'cooldowns', ['agent_name'], unique=False)
    op.create_index(op.f('ix_cooldowns_contact_id'), 'cooldowns', ['contact_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'TEMPLATE', 'IMAGE', 'DOCUMENT', 'VIDEO', 'BUTTON', 'INTERACTIVE', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='Message body text'),
    sa.Column('template_name', sa.String(length=200), nullable=True, comment='Meta template name (for template messages)'),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'REJECTED', name='messagestatus'), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True, comment="Meta's wamid (WhatsApp Message ID) for deduplication"),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='Which agent sent (outbound) or should receive (inbound) this message'),
    sa.Column('classification', sa.String(length=50), nullable=True, comment='AI classification: interested, not_interested, question, complaint, opt_out, etc.'),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Template components, media URLs, error details, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_messages_agent_name'), 'messages', ['agent_name'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_name'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_cooldowns_contact_id'), table_name='cooldowns')
    op.drop_index(op.f('ix_cooldowns_agent_name'), table_name='cooldowns')
    op.drop_table('cooldowns')
    op.drop_index(op.f('ix_conversations_owning_agent'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_contact_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_agent_registrations_name'), table_name='agent_registrations')
    op.drop_table('agent_registrations')
    # ### end Alembic commands ###
