"""Verify the broker's audit chain — in the cloud, against the bucket.

WHY THIS FILE EXISTS AT ALL. The Mac verifies its own log (`AstraBroker
verify-audit`), and that is worth exactly nothing against the threat
this design names: a party who can rewrite the log can also rewrite the
verifier that reads it. The chain only becomes evidence when a second
party, holding a credential the first one has never had, recomputes it
from objects the first one cannot delete. That party is this module,
running on Railway with a bucket-scoped READ-ONLY R2 token, over an
`astra-audit` bucket under an indefinite Bucket Lock.

So the rule for everything below: it recomputes, it never trusts. Every
hash is recomputed from the record's own fields. Every signature is
verified against the chain id — which is the Ed25519 public key, and
which Kunal keeps on his phone, not in this repo and not in the bucket.

TWO THINGS ARE EASY TO GET WRONG AND BOTH ARE FATAL.

1. THE FLOOR. `chain.json` carries `first_seq`: the lowest seq the
   bucket holds. It has to, because the anchor was enrolled MID-LOG —
   the deployed pre-A7 broker had already written records whose
   verb/reason fields carry brain-chosen text, and those bytes must
   never reach a bucket that cannot delete them. So seqs below
   `first_seq` are absent BY DESIGN and the verifier must not call
   them tampering.

   That makes `first_seq` the single most attackable number in the
   system: anyone holding the WRITER token (including the one shared in
   a screenshot, live until it is rotated) could put a manifest
   claiming `first_seq: 1000000`, and under the lock that lie is
   permanent and every hole below it invisible. Hence: the manifest is
   signed with the same key that signs the records, and this module
   verifies that signature BEFORE it reads `first_seq` for any purpose.
   An unsigned manifest is not a manifest. The construction is pinned
   in `astra-broker/Resources/audit_anchor_vectors.json`, which is
   generated by Python and asserted by the Swift suite, so the two
   sides cannot drift apart quietly.

2. A GAP IS TAMPERING UNTIL PROVED OTHERWISE. `intent_events` and this
   chain share one rule: a missing seq means the record was removed.
   The one exception is a seq the operator deliberately stepped over
   (`audit-sink-reconcile --skip-seq`), and it is an exception only
   because it leaves its own signed, permanent object at
   `chains/<id>/skips/<12-digit seq>.json`. No skip object, or a skip
   object this key did not sign, and the gap is a gap. Note what this
   buys: to hide a record you must publish a signed statement that you
   hid it, using a key that lives inside uid 450 on the Mac — and the
   statement is as undeletable as the record would have been.

   A skipped seq also breaks the prev_hash walk (the bucket has no
   record to hash), so linkage is unverifiable across exactly that seq
   and nowhere else. That hole is named in the verdict, never silently
   bridged.

WHAT THIS MODULE DOES NOT DO. It performs no I/O: no boto3, no
database, no network. Everything here is a pure function over parsed
JSON, so the acceptance tests run offline and the reader in
`audit_anchor.py` is the only thing that has to be stubbed. The
cross-check against `intent_events` is here too, as a pure function
over rows the caller fetched, because it is chain logic, not transport.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping, Sequence

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

# ── the shared constants, identical to Sources/AstraCore/Audit.swift ──

UNIT = b"\x1f"
GENESIS = "0" * 64

RECORD_SIG_PREFIX = b"astra-audit-v1\x00"
HEAD_SIG_PREFIX = b"astra-audit-head-v1\x00"
CHAIN_SIG_PREFIX = b"astra-audit-chain-v1\x00"
SKIP_SIG_PREFIX = b"astra-audit-skip-v1\x00"

#: The eleven keys of one audit line, in the order the hash joins them
#: (`record_hash` and `prev_hash` are not in the join list; `prev_hash`
#: leads it). Kept as data so a missing field is a named failure rather
#: than a KeyError three frames down.
HASHED_FIELDS = (
    "seq",
    "ts_ms",
    "decision",
    "verb",
    "intent_id",
    "args_sha256",
    "display_sha256",
    "receipt_sha256",
    "reason",
)

#: The cross-language contract for the four signing constructions. This
#: module IS the reference implementation (RFC 8032 Ed25519 is
#: deterministic; CryptoKit's signing is randomised, so Swift cannot pin
#: a signature) — the file is generated from these same constructions by
#: astra-broker/Tests/check_audit_anchor_vectors.py, asserted against
#: Swift by AuditAnchorVectorTests, and asserted against THIS module by
#: tests/test_broker/test_audit_chain.py. Three places, one construction.
ANCHOR_VECTORS_PATH = (
    pathlib.Path(__file__).resolve().parents[2].parent
    / "astra-broker/Resources/audit_anchor_vectors.json"
)

_HEX64 = re.compile(r"\A[0-9a-f]{64}\Z")


class BadObject(ValueError):
    """A bucket object is not the shape this verifier requires.

    Raised only for structural failures (not JSON, missing field, wrong
    type). A *well-formed* object that fails a check produces a
    Verdict, never an exception, because a verdict is what gets
    reported and stored.
    """


def load_anchor_vectors() -> dict[str, Any]:
    if not ANCHOR_VECTORS_PATH.exists():
        raise FileNotFoundError(
            f"audit-anchor vector file missing at {ANCHOR_VECTORS_PATH} — the "
            "Swift shipper and this verifier are held to the SAME file; "
            "without it neither side proves anything about the other."
        )
    return json.loads(ANCHOR_VECTORS_PATH.read_text())


def be64(n: int) -> bytes:
    if n < 0 or n > 0xFFFF_FFFF_FFFF_FFFF:
        raise BadObject(f"{n} does not fit in a uint64")
    return n.to_bytes(8, "big")


def _hex_bytes(h: str) -> bytes:
    """Hex to bytes, refusing anything that is not a 64-char digest.

    Swift's `hexBytes` skips characters it cannot parse rather than
    failing, which is right for a parser and wrong for a verifier: a
    signature over a silently-shortened digest would verify against a
    different fact than the one on screen.
    """
    if not isinstance(h, str) or not _HEX64.match(h):
        raise BadObject(f"not a 64-character lowercase hex digest: {h!r}")
    return bytes.fromhex(h)


# ── the constructions ────────────────────────────────────────────────


def record_hash(rec: Mapping[str, Any]) -> str:
    """Recompute a record's hash from its own fields.

    sha256( prev_hash ‖ 0x1F ‖ seq ‖ 0x1F ‖ ts_ms ‖ 0x1F ‖ decision
            ‖ 0x1F ‖ verb ‖ 0x1F ‖ intent_id ‖ 0x1F ‖ args_sha256
            ‖ 0x1F ‖ display_sha256 ‖ 0x1F ‖ receipt_sha256
            ‖ 0x1F ‖ reason ), as lowercase hex.

    The numbers are joined as their DECIMAL strings, exactly as Swift's
    `String(seq)` writes them — not as fixed-width bytes.
    """
    parts: list[str] = []
    for f in ("prev_hash",) + HASHED_FIELDS:
        if f not in rec:
            raise BadObject(f"record is missing the field {f!r}")
        v = rec[f]
        if f in ("seq", "ts_ms"):
            # Decimal, exactly as Swift's String(seq) writes it. A float
            # here would render as "13.0" and hash to something else,
            # so the type is checked rather than coerced.
            if isinstance(v, bool) or not isinstance(v, int):
                raise BadObject(f"record field {f!r} is {type(v).__name__}, not an integer")
            parts.append(str(v))
        else:
            if not isinstance(v, str):
                raise BadObject(f"record field {f!r} is {type(v).__name__}, not a string")
            parts.append(v)
    joined = "\x1f".join(parts)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()


def record_signing_bytes(rec_hash: str) -> bytes:
    """The record's own record_hash, as BYTES, never the hex."""
    return RECORD_SIG_PREFIX + _hex_bytes(rec_hash)


def head_signing_bytes(seq: int, rec_hash: str, ts_ms: int) -> bytes:
    return HEAD_SIG_PREFIX + be64(seq) + _hex_bytes(rec_hash) + be64(ts_ms)


def chain_signing_bytes(
    chain_id: str, first_seq: int, first_prev_hash: str, created_ms: int
) -> bytes:
    """The FLOOR: where the anchor begins and what it chains onto."""
    return (
        CHAIN_SIG_PREFIX
        + chain_id.encode("utf-8")
        + UNIT
        + be64(first_seq)
        + _hex_bytes(first_prev_hash)
        + be64(created_ms)
    )


def skip_signing_bytes(chain_id: str, seq: int, why: str, skipped_ms: int) -> bytes:
    """A gap made on purpose. `why` is a closed code, never bytes."""
    return (
        SKIP_SIG_PREFIX
        + chain_id.encode("utf-8")
        + UNIT
        + be64(seq)
        + why.encode("utf-8")
        + UNIT
        + be64(skipped_ms)
    )


def public_key(chain_id: str) -> Ed25519PublicKey:
    """The chain id IS the public key. That is the whole root of trust.

    Kunal's phone holds this 64-hex string; the bucket holds everything
    else. A verifier pinned to it cannot be fooled by a second chain
    written under the same writer token, which is the one forgery the
    lock does not prevent.
    """
    if not isinstance(chain_id, str) or not _HEX64.match(chain_id):
        raise BadObject(f"chain id is not 64 lowercase hex characters: {chain_id!r}")
    return Ed25519PublicKey.from_public_bytes(bytes.fromhex(chain_id))


def _verifies(pub: Ed25519PublicKey, sig_hex: str, msg: bytes) -> bool:
    if not isinstance(sig_hex, str) or len(sig_hex) != 128:
        return False
    try:
        sig = bytes.fromhex(sig_hex)
    except ValueError:
        return False
    try:
        pub.verify(sig, msg)
    except InvalidSignature:
        return False
    return True


# ── verdicts ─────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Verdict:
    """One finding, named precisely enough to act on at 3am.

    `ok` is the only thing a caller may branch on to mean "fine". Every
    other kind is a failure with a `seq` range in its text, because a
    verifier that says "something is wrong" and not "seq 41 is missing"
    trains its reader to ignore it.
    """

    kind: str
    detail: str
    seq: int | None = None
    next_seq: int | None = None
    count: int = 0

    @property
    def ok(self) -> bool:
        return self.kind == "intact"

    def __str__(self) -> str:
        return self.detail

    def __bool__(self) -> bool:  # pragma: no cover - guard, not logic
        raise TypeError(
            "a Verdict is never truthy by accident: branch on .ok, so "
            "'if verify(...)' cannot silently mean 'it passed'."
        )


def _intact(n: int, first: int, last: int) -> Verdict:
    return Verdict(
        kind="intact",
        detail=f"chain intact across {n} records (seq {first}..{last})",
        seq=first,
        next_seq=last,
        count=n,
    )


# ── the manifest ─────────────────────────────────────────────────────


@dataclass(frozen=True)
class Manifest:
    chain_id: str
    audit_pubkey: str
    first_seq: int
    first_prev_hash: str
    created_ms: int
    body: str = ""
    broker_cdhash: str = ""


def verify_manifest(obj: Mapping[str, Any], chain_id: str) -> tuple[Manifest | None, Verdict]:
    """Check chain.json's signature BEFORE trusting a single field of it.

    Returns (manifest, verdict). The manifest is None on any failure —
    callers cannot accidentally read `first_seq` off a rejected
    manifest, because there is nothing to read it from.

    `chain_id` is the caller's PIN (from the phone runbook / the
    AUDIT_CHAIN_ID env), not the file's own claim. A manifest that
    names a different chain is a different chain, however well signed.
    """
    if not isinstance(obj, Mapping):
        return None, Verdict("manifest_malformed", "chain.json is not a JSON object")
    claimed = obj.get("chain_id")
    if claimed != chain_id:
        return None, Verdict(
            "manifest_foreign",
            f"chain.json names chain {claimed!r}, not the pinned chain {chain_id!r}; "
            "a writer token can create any number of chains, so the pin — not the "
            "bucket — decides which one is Kunal's",
        )
    pubkey = obj.get("audit_pubkey")
    if pubkey != chain_id:
        return None, Verdict(
            "manifest_foreign_key",
            f"chain.json's audit_pubkey {pubkey!r} is not the chain id {chain_id!r}; "
            "the chain id IS the public key, so these can never differ honestly",
        )
    sig = obj.get("sig")
    if not isinstance(sig, str) or not sig:
        return None, Verdict(
            "manifest_unsigned",
            "chain.json carries NO signature over its floor. An unsigned manifest is "
            "an unauthenticated claim about which seqs are missing on purpose — "
            "exactly the claim an attacker with the writer token would want to make, "
            "permanently, under the bucket lock. Refusing to read first_seq from it.",
        )
    try:
        first_seq = int(obj["first_seq"])
        first_prev = str(obj["first_prev_hash"])
        created_ms = int(obj["created_ms"])
        msg = chain_signing_bytes(chain_id, first_seq, first_prev, created_ms)
    except (KeyError, TypeError, ValueError, BadObject) as e:
        return None, Verdict(
            "manifest_malformed", f"chain.json's floor fields are unusable: {e}"
        )
    if not _verifies(public_key(chain_id), sig, msg):
        return None, Verdict(
            "manifest_sig_invalid",
            f"chain.json's signature does not verify under chain {chain_id}: the "
            f"claimed floor (first_seq={first_seq}, first_prev_hash={first_prev}) was "
            "not signed by the broker's audit key. Treat first_seq as unknown; every "
            "seq below it is a HOLE, not a design decision.",
        )
    if first_seq < 1:
        return None, Verdict(
            "manifest_malformed", f"chain.json claims first_seq={first_seq}, below 1"
        )
    if first_seq == 1 and first_prev != GENESIS:
        return None, Verdict(
            "manifest_malformed",
            f"chain.json claims first_seq=1 but first_prev_hash={first_prev}, not "
            "genesis; a chain that starts at seq 1 starts at the genesis link",
        )
    return (
        Manifest(
            chain_id=chain_id,
            audit_pubkey=str(pubkey),
            first_seq=first_seq,
            first_prev_hash=first_prev,
            created_ms=created_ms,
            body=str(obj.get("body", "")),
            broker_cdhash=str(obj.get("broker_cdhash", "")),
        ),
        Verdict(
            "manifest_ok",
            f"chain.json verifies: chain {chain_id} anchors from seq {first_seq} "
            f"(prev {first_prev[:16]}…), announced {created_ms}",
            seq=first_seq,
        ),
    )


# ── signed step-overs ────────────────────────────────────────────────


@dataclass(frozen=True)
class Skip:
    seq: int
    why: str
    skipped_ms: int


def verify_skips(
    objects: Mapping[int, Mapping[str, Any]], chain_id: str
) -> tuple[dict[int, Skip], list[Verdict]]:
    """Which absences are decisions. Unsigned ones are NOT decisions.

    `objects` maps the seq named by the KEY (`skips/<12 digits>.json`)
    to the parsed object. A skip whose body names a different seq is
    discarded: the key and the body must agree, or a single signed
    object could excuse any seq the attacker liked by renaming it.
    """
    good: dict[int, Skip] = {}
    problems: list[Verdict] = []
    pub = public_key(chain_id)
    for key_seq, obj in sorted(objects.items()):
        if not isinstance(obj, Mapping):
            problems.append(
                Verdict("skip_malformed", f"skips/{key_seq:012d}.json is not an object", seq=key_seq)
            )
            continue
        try:
            body_seq = int(obj["seq"])
            why = str(obj["why"])
            ms = int(obj["skipped_ms"])
            sig = str(obj["sig"])
            cid = str(obj["chain_id"])
        except (KeyError, TypeError, ValueError):
            problems.append(
                Verdict(
                    "skip_malformed",
                    f"skips/{key_seq:012d}.json is missing a field this verifier signs over",
                    seq=key_seq,
                )
            )
            continue
        if cid != chain_id or body_seq != key_seq:
            problems.append(
                Verdict(
                    "skip_mismatched",
                    f"skips/{key_seq:012d}.json names seq {body_seq} of chain {cid[:16]}…; "
                    "the key and the signed body must agree or one signature excuses "
                    "any seq",
                    seq=key_seq,
                )
            )
            continue
        if not _verifies(pub, sig, skip_signing_bytes(chain_id, body_seq, why, ms)):
            problems.append(
                Verdict(
                    "skip_sig_invalid",
                    f"skips/{key_seq:012d}.json is NOT signed by chain {chain_id[:16]}…; "
                    f"seq {key_seq} stays a hole, not a decision",
                    seq=key_seq,
                )
            )
            continue
        good[key_seq] = Skip(seq=body_seq, why=why, skipped_ms=ms)
    return good, problems


# ── the chain walk ───────────────────────────────────────────────────


@dataclass
class ChainReport:
    """Everything one verification run learned, in report order."""

    verdict: Verdict
    manifest: Manifest | None = None
    records: int = 0
    first_seq: int | None = None
    head_seq: int | None = None
    head_hash: str = ""
    skipped: dict[int, Skip] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.verdict.ok

    def __str__(self) -> str:
        return str(self.verdict)


def verify_chain(
    objects: Sequence[Mapping[str, Any]],
    chain_id: str,
    manifest: Manifest | None = None,
    skips: Mapping[int, Skip] | None = None,
) -> ChainReport:
    """Recompute every hash and every signature, in seq order.

    `objects` are the parsed `records/<seq>.json` wrappers
    ({"chain_id", "record", "shipped_ms", "sig"}), in any order. The
    FIRST problem is returned, naming its seq — a report that lists
    forty consequences of one deletion is a report nobody reads.

    Order of checks is deliberate. Signature first (is this ours?),
    then the hash (do the bytes match the hash they carry?), then the
    link (does it chain onto its predecessor?), then the sequence (is
    anything missing?). Each answers a different question and the
    earlier ones make the later ones meaningful.
    """
    skips = dict(skips or {})
    if not objects:
        return ChainReport(
            verdict=Verdict(
                "empty",
                f"chain {chain_id} holds no records at all. An empty anchor is not a "
                "clean bill of health: it is what a chain that was never shipped and "
                "a chain whose objects were never created both look like.",
            ),
            manifest=manifest,
            skipped=skips,
        )

    pub = public_key(chain_id)
    parsed: list[tuple[int, Mapping[str, Any], str, str]] = []  # seq, record, stored, sig
    for wrapper in objects:
        if not isinstance(wrapper, Mapping) or not isinstance(wrapper.get("record"), Mapping):
            return ChainReport(
                verdict=Verdict(
                    "malformed", "a records/ object has no `record` member", seq=None
                ),
                manifest=manifest,
                skipped=skips,
            )
        rec = wrapper["record"]
        cid = wrapper.get("chain_id")
        try:
            seq = int(rec["seq"])
            stored = str(rec["record_hash"])
        except (KeyError, TypeError, ValueError):
            return ChainReport(
                verdict=Verdict("malformed", "a records/ object has no seq/record_hash"),
                manifest=manifest,
                skipped=skips,
            )
        if cid != chain_id:
            return ChainReport(
                verdict=Verdict(
                    "foreign_object",
                    f"the object at seq {seq} belongs to chain {str(cid)[:16]}…, not to "
                    f"the pinned chain {chain_id[:16]}…",
                    seq=seq,
                ),
                manifest=manifest,
                skipped=skips,
            )
        parsed.append((seq, rec, stored, str(wrapper.get("sig", ""))))

    parsed.sort(key=lambda t: t[0])
    seqs = [p[0] for p in parsed]
    dupes = {s for s in seqs if seqs.count(s) > 1}
    if dupes:
        d = sorted(dupes)[0]
        return ChainReport(
            verdict=Verdict(
                "duplicate",
                f"seq {d} appears more than once in the bucket. Every put is "
                "create-only, so two objects under one seq mean two different chains "
                "were written under one chain id.",
                seq=d,
            ),
            manifest=manifest,
            skipped=skips,
        )

    notes: list[str] = []

    # THE FLOOR. Below first_seq, absence is by design — but only when
    # a VERIFIED manifest said so. Without one, seq 1 is the only
    # honest starting point, because "the beginning was removed" and
    # "the anchor began later" are the same picture.
    first = seqs[0]
    if manifest is not None:
        if first != manifest.first_seq:
            return ChainReport(
                verdict=Verdict(
                    "floor_mismatch",
                    f"the signed manifest anchors this chain at seq {manifest.first_seq} "
                    f"but the lowest record in the bucket is seq {first}: "
                    + (
                        f"seqs {manifest.first_seq}..{first - 1} are missing and nothing "
                        "signed says they should be"
                        if first > manifest.first_seq
                        else "the bucket holds records BELOW the floor it announced"
                    ),
                    seq=manifest.first_seq,
                    next_seq=first,
                ),
                manifest=manifest,
                skipped=skips,
            )
        if str(parsed[0][1].get("prev_hash")) != manifest.first_prev_hash:
            return ChainReport(
                verdict=Verdict(
                    "floor_mismatch",
                    f"seq {first} chains onto {parsed[0][1].get('prev_hash')}, but the "
                    f"signed manifest says the anchor begins after "
                    f"{manifest.first_prev_hash}",
                    seq=first,
                ),
                manifest=manifest,
                skipped=skips,
            )
        if manifest.first_seq > 1:
            notes.append(
                f"anchor begins mid-log at seq {manifest.first_seq} by signed design "
                f"(prev {manifest.first_prev_hash[:16]}…); seqs 1..{manifest.first_seq - 1} "
                "are in the Mac's local log only"
            )
    elif first != 1:
        return ChainReport(
            verdict=Verdict(
                "no_floor",
                f"the bucket's lowest record is seq {first} and there is no VERIFIED "
                "chain.json to say the anchor starts there by design. Until the "
                f"manifest verifies, seqs 1..{first - 1} are missing.",
                seq=1,
                next_seq=first,
            ),
            manifest=None,
            skipped=skips,
        )

    prev_hash: str | None = manifest.first_prev_hash if manifest else GENESIS
    prev_seq: int | None = None

    for seq, rec, stored, sig in parsed:
        # 1. is this ours?
        try:
            msg = record_signing_bytes(stored)
        except BadObject as e:
            return ChainReport(
                verdict=Verdict("malformed", f"seq {seq}: {e}", seq=seq),
                manifest=manifest,
                skipped=skips,
            )
        if not _verifies(pub, sig, msg):
            return ChainReport(
                verdict=Verdict(
                    "sig_invalid",
                    f"seq {seq}: the object's signature does not verify under chain "
                    f"{chain_id[:16]}…. Someone with the writer token re-signed or "
                    "replaced this record with a key that is not the broker's.",
                    seq=seq,
                ),
                manifest=manifest,
                skipped=skips,
            )
        # 2. do the bytes match the hash they carry?
        try:
            computed = record_hash(rec)
        except BadObject as e:
            return ChainReport(
                verdict=Verdict("malformed", f"seq {seq}: {e}", seq=seq),
                manifest=manifest,
                skipped=skips,
            )
        if computed != stored:
            return ChainReport(
                verdict=Verdict(
                    "tampered",
                    f"seq {seq}: a field was edited. The record hashes to {computed} "
                    f"but carries {stored}.",
                    seq=seq,
                ),
                manifest=manifest,
                skipped=skips,
            )
        # 3. is anything missing between the last seq and this one?
        if prev_seq is not None and seq != prev_seq + 1:
            missing = [n for n in range(prev_seq + 1, seq)]
            unexcused = [n for n in missing if n not in skips]
            if unexcused:
                return ChainReport(
                    verdict=Verdict(
                        "gap",
                        f"seq {unexcused[0]} is missing (the bucket jumps from "
                        f"{prev_seq} to {seq}; {len(unexcused)} of the "
                        f"{len(missing)} absent seqs have no signed skips/ object). "
                        "Under an indefinite bucket lock a record cannot go missing "
                        "by accident.",
                        seq=prev_seq,
                        next_seq=seq,
                    ),
                    manifest=manifest,
                    skipped=skips,
                )
            for n in missing:
                notes.append(
                    f"seq {n} absent by a signed, permanent skips/ object "
                    f"(why={skips[n].why}); the link across it is unverifiable BY "
                    "DESIGN and is not checked"
                )
            # The skipped record's hash is not in the bucket, so the
            # next record's prev_hash cannot be recomputed. The break
            # is accepted here and NOWHERE else.
            prev_hash = None
        # 4. does it chain onto its predecessor?
        if prev_hash is not None and str(rec.get("prev_hash")) != prev_hash:
            return ChainReport(
                verdict=Verdict(
                    "broken_link",
                    f"seq {seq}: prev_hash is {rec.get('prev_hash')} but seq "
                    f"{prev_seq if prev_seq is not None else seq - 1} hashes to "
                    f"{prev_hash}. The chain forks here.",
                    seq=seq,
                ),
                manifest=manifest,
                skipped=skips,
            )
        prev_hash = stored
        prev_seq = seq

    # A skip object for a seq the bucket actually holds is a
    # contradiction: someone signed "this is absent" over a record that
    # is present. Reported, because it means the operator and the
    # bucket disagree about what happened.
    contradicted = sorted(set(skips) & set(seqs))
    if contradicted:
        return ChainReport(
            verdict=Verdict(
                "skip_contradicted",
                f"seq {contradicted[0]} has BOTH a record and a signed skips/ object "
                "saying it was stepped over. One of the two is a lie and both are "
                "permanent.",
                seq=contradicted[0],
            ),
            manifest=manifest,
            records=len(parsed),
            skipped=skips,
            notes=notes,
        )

    return ChainReport(
        verdict=_intact(len(parsed), seqs[0], seqs[-1]),
        manifest=manifest,
        records=len(parsed),
        first_seq=seqs[0],
        head_seq=seqs[-1],
        head_hash=parsed[-1][2],
        skipped=skips,
        notes=notes,
    )


# ── the newest head object ───────────────────────────────────────────


def verify_head(
    obj: Mapping[str, Any], chain_id: str, report: ChainReport
) -> Verdict:
    """A head is a signed statement about where the chain ended.

    It is checked against the records because the two are written at
    different times by the same key: a head naming a seq ABOVE the
    newest record is the strongest evidence there is that records were
    removed after they were anchored — the broker itself said they
    existed.
    """
    try:
        seq = int(obj["seq"])
        rec_hash = str(obj["record_hash"])
        ts_ms = int(obj["ts_ms"])
        sig = str(obj["sig"])
    except (KeyError, TypeError, ValueError):
        return Verdict("head_malformed", "the newest heads/ object is missing a field")
    if not _verifies(
        public_key(chain_id), sig, head_signing_bytes(seq, rec_hash, ts_ms)
    ):
        return Verdict(
            "head_sig_invalid",
            f"the newest heads/ object (seq {seq}) is not signed by chain "
            f"{chain_id[:16]}…",
            seq=seq,
        )
    if report.head_seq is None:
        return Verdict("head_ok", f"head at seq {seq}, no records to compare", seq=seq)
    if seq > report.head_seq:
        return Verdict(
            "head_ahead",
            f"the broker signed a head at seq {seq} but the bucket's newest record is "
            f"seq {report.head_seq}. Records {report.head_seq + 1}..{seq} were "
            "anchored and are now absent.",
            seq=report.head_seq,
            next_seq=seq,
        )
    if seq == report.head_seq and rec_hash != report.head_hash:
        return Verdict(
            "head_mismatch",
            f"the head names seq {seq} with hash {rec_hash} but the record at that seq "
            f"hashes to {report.head_hash}",
            seq=seq,
        )
    return Verdict(
        "head_ok",
        f"newest head agrees with the chain at seq {seq}",
        seq=seq,
    )


# ── the low-trust second copy ────────────────────────────────────────


@dataclass
class CrossCheck:
    missing_in_r2: list[int] = field(default_factory=list)
    missing_in_pg: list[int] = field(default_factory=list)
    hash_mismatch: list[int] = field(default_factory=list)
    below_floor: list[int] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not (self.missing_in_r2 or self.missing_in_pg or self.hash_mismatch)

    def __str__(self) -> str:
        if self.ok:
            n = len(self.below_floor)
            tail = f" ({n} pre-anchor seqs below the floor, expected)" if n else ""
            return "R2 and intent_events agree" + tail
        return (
            f"missing_in_r2={self.missing_in_r2} missing_in_pg={self.missing_in_pg} "
            f"hash_mismatch={self.hash_mismatch}"
        )


def cross_check(
    r2_records: Iterable[Mapping[str, Any]],
    pg_rows: Iterable[Mapping[str, Any]],
    first_seq: int = 1,
    skips: Iterable[int] = (),
) -> CrossCheck:
    """Compare the anchor with the queryable mirror.

    The mirror is the LOW-TRUST copy — it lives in the database the
    brain holds a superuser role on, which is exactly why a
    disagreement is interesting and why the anchor wins every one of
    them. Seqs below `first_seq` are the pre-anchor records: present in
    Postgres, absent from the bucket by design, and reported separately
    so they never read as a hole.
    """
    skipped = set(skips)
    r2 = {int(r["seq"]): str(r["record_hash"]) for r in r2_records}
    pg = {int(r["seq"]): str(r.get("record_hash") or "") for r in pg_rows}
    out = CrossCheck()
    for seq in sorted(set(r2) | set(pg)):
        if seq in r2 and seq not in pg:
            out.missing_in_pg.append(seq)
        elif seq in pg and seq not in r2:
            if seq < first_seq:
                out.below_floor.append(seq)
            elif seq not in skipped:
                out.missing_in_r2.append(seq)
        elif r2.get(seq) != pg.get(seq):
            out.hash_mismatch.append(seq)
    return out
