"""initial schema — 8 tables

Revision ID: 387c77b34537
Revises: 
Create Date: 2026-04-02 22:30:50.774535
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '387c77b34537'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('emails_received', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_category'), 'contacts', ['category'], unique=False)
    op.create_index(op.f('ix_contacts_email_address'), 'contacts', ['email_address'], unique=True)
    op.create_table('email_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gmail_history_id', sa.String(length=50), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_email_address'), 'email_accounts', ['email_address'], unique=True)
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('subject_template', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gmail_label_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('label_type', sa.String(length=20), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_label_id')
    )
    op.create_table('email_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_priority', sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='threadpriority'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_category', sa.String(length=50), nullable=True),
    sa.Column('needs_response', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_gmail_thread_id'), 'email_threads', ['gmail_thread_id'], unique=True)
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='emaildirection'), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('cc_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('bcc_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('gmail_labels', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('ai_category', sa.String(length=50), nullable=True),
    sa.Column('ai_priority', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.String(length=500), nullable=True),
    sa.Column('ai_action_needed', sa.Boolean(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_messages_account_sent', 'email_messages', ['account_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_email_messages_ai_category'), 'email_messages', ['ai_category'], unique=False)
    op.create_index('ix_email_messages_direction', 'email_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_message_id'), 'email_messages', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_email_messages_gmail_thread_id'), 'email_messages', ['gmail_thread_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('reply_to_message_id', sa.UUID(), nullable=True),
    sa.Column('to_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('cc_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'APPROVED', 'SENT', 'DISCARDED', name='draftstatus'), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gmail_draft_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('to_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('cc_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', 'CANCELLED', name='schedulestatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_emails_scheduled_for'), 'scheduled_emails', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_emails_scheduled_for'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_email_messages_gmail_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_gmail_message_id'), table_name='email_messages')
    op.drop_index('ix_email_messages_direction', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_ai_category'), table_name='email_messages')
    op.drop_index('ix_email_messages_account_sent', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_gmail_thread_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_table('labels')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_accounts_email_address'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_contacts_email_address'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_category'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
